apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: shopapp
type: Opaque
stringData:
  username: admin
  password: secret123
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: shopapp
type: Opaque
stringData:
  jwt-secret: mysupersecretjwtkey123
  mongo-uri: mongodb://admin:secret123@mongodb:27017/shopapp?authSource=admin
